# Generated by Django 3.2.3 on 2021-06-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cSex',
        ),
    ]
