# Generated by Django 3.2.3 on 2021-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0003_auto_20210609_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='person_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
