# Generated by Django 3.2.3 on 2021-06-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0004_auto_20210609_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person_account',
            new_name='personal_account',
        ),
    ]
