# Generated by Django 3.2.3 on 2021-06-13 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0005_rename_person_account_personal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_account',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
