# Generated by Django 3.2.3 on 2021-06-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0006_personal_account_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personal_account',
            new_name='Personal',
        ),
    ]
